export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_INITIALIZED = 'AUTHENTICATE_INITIALIZED';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';
export const AUTHENTICATE_LOGOUT = 'AUTHENTICATE_LOGOUT';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_INITIALIZED = 'FETCH_POSTS_INITIALIZED';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const SAVE_POST = 'SAVE_POST';
export const SAVE_POST_INITIALIZED = 'SAVE_POST_INITIALIZED';
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS';
export const SAVE_POST_FAILURE = 'SAVE_POST_FAILURE';

export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_INITIALIZED = 'EDIT_POST_INITIALIZED';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_INITIALIZED = 'DELETE_POST_INITIALIZED';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';
